// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file nested.proto (package testdata, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

import { fileDesc } from "protoc-gen-es-string-descriptor";
/**
 * Describes the file nested.proto.
 */
export const file_nested: GenFile = /*@__PURE__*/
  fileDesc("" +
    "\n" +
    "\fnested.proto\x12\btestdata\"\x88\x01\n" +
    "\x05Outer\x12\f\n" +
    "\x04name\x18\x01 \x01(\t\x12$\n" +
    "\x05inner\x18\x02 \x01(\v2\x15.testdata.Outer.Inner\x12$\n" +
    "\x05items\x18\x03 \x03(\v2\x15.testdata.Outer.Inner\x1a%\n" +
    "\x05Inner\x12\r\n" +
    "\x05value\x18\x01 \x01(\t\x12\r\n" +
    "\x05count\x18\x02 \x01(\x05b\x06proto3\xd2\xf6\x03\x04\b\x00\x18\x00");

/**
 * @generated from message testdata.Outer
 */
export type Outer = Message<"testdata.Outer"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: testdata.Outer.Inner inner = 2;
   */
  inner?: Outer_Inner;

  /**
   * @generated from field: repeated testdata.Outer.Inner items = 3;
   */
  items: Outer_Inner[];
};

/**
 * Describes the message testdata.Outer.
 * Use `create(OuterSchema)` to create a new message.
 */
export const OuterSchema: GenMessage<Outer> = /*@__PURE__*/
  messageDesc(file_nested, 0);

/**
 * @generated from message testdata.Outer.Inner
 */
export type Outer_Inner = Message<"testdata.Outer.Inner"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * @generated from field: int32 count = 2;
   */
  count: number;
};

/**
 * Describes the message testdata.Outer.Inner.
 * Use `create(Outer_InnerSchema)` to create a new message.
 */
export const Outer_InnerSchema: GenMessage<Outer_Inner> = /*@__PURE__*/
  messageDesc(file_nested, 0, 0);

