// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file simple.proto (package testdata, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

import { fileDesc } from "protoc-gen-es-string-descriptor";
/**
 * Describes the file simple.proto.
 */
export const file_simple: GenFile = /*@__PURE__*/
  fileDesc("" +
    "\n" +
    "\fsimple.proto\x12\btestdata\"0\n" +
    "\x04User\x12\f\n" +
    "\x04name\x18\x01 \x01(\t\x12\v\n" +
    "\x03age\x18\x02 \x01(\x05\x12\r\n" +
    "\x05email\x18\x03 \x01(\t*H\n" +
    "\x06Status\x12\x16\n" +
    "\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
    "\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
    "\x0fSTATUS_INACTIVE\x10\x02b\x06proto3\xd2\xf6\x03\x04\b\x00\x18\x00");

/**
 * @generated from message testdata.User
 */
export type User = Message<"testdata.User"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 age = 2;
   */
  age: number;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message testdata.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_simple, 0);

/**
 * @generated from enum testdata.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,
}

/**
 * Describes the enum testdata.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_simple, 0);

